testserver:
	g++ -o Echo_server_1 Echo_server_1.cc -lmymuduo -lpthread
	g++ -o Echo_server_2 Echo_server_2.cc -lmymuduo -lpthread
	g++ -o Echo_server_3 Echo_server_3.cc -lmymuduo -lpthread
clean:
	rm -f Echo_server_1
	rm -f Echo_server_2
	rm -f Echo_server_3